# ruff: noqa: E501

"""
Demo universe data for the screener engine.

Provides a realistic set of 30 large-cap equities with
pre-computed fundamental and technical fields for UI development.
Real data will come from TimescaleDB + yfinance fundamentals.
"""

from __future__ import annotations

DEMO_UNIVERSE: list[dict] = [
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 3_000_000,
        "price": 198.75,
        "change_pct_1d": 0.82,
        "pe_ratio": 32.1,
        "pb_ratio": 47.2,
        "ps_ratio": 8.1,
        "dividend_yield": 0.5,
        "revenue_growth": 2.8,
        "eps_growth": 10.2,
        "profit_margin": 25.3,
        "debt_to_equity": 1.95,
        "rsi_14": 56.2,
        "macd_signal": 0.42,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 24.1,
        "atr_pct": 1.1,
        "volume_ratio": 1.2,
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft Corporation",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 3_200_000,
        "price": 420.50,
        "change_pct_1d": 0.44,
        "pe_ratio": 36.5,
        "pb_ratio": 14.2,
        "ps_ratio": 12.4,
        "dividend_yield": 0.7,
        "revenue_growth": 15.2,
        "eps_growth": 20.1,
        "profit_margin": 35.1,
        "debt_to_equity": 0.35,
        "rsi_14": 62.1,
        "macd_signal": 1.20,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 31.0,
        "atr_pct": 0.9,
        "volume_ratio": 0.9,
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 2_400_000,
        "price": 498.50,
        "change_pct_1d": 1.85,
        "pe_ratio": 65.8,
        "pb_ratio": 30.5,
        "ps_ratio": 24.8,
        "dividend_yield": 0.1,
        "revenue_growth": 122.4,
        "eps_growth": 288.0,
        "profit_margin": 55.0,
        "debt_to_equity": 0.42,
        "rsi_14": 71.3,
        "macd_signal": 5.20,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 45.2,
        "atr_pct": 2.4,
        "volume_ratio": 1.8,
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet Inc. Class A",
        "sector": "Communication",
        "exchange": "NASDAQ",
        "market_cap": 2_100_000,
        "price": 170.25,
        "change_pct_1d": -0.32,
        "pe_ratio": 23.8,
        "pb_ratio": 6.8,
        "ps_ratio": 6.2,
        "dividend_yield": 0.0,
        "revenue_growth": 11.8,
        "eps_growth": 30.5,
        "profit_margin": 24.0,
        "debt_to_equity": 0.06,
        "rsi_14": 48.5,
        "macd_signal": -0.20,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 18.3,
        "atr_pct": 1.0,
        "volume_ratio": 0.7,
    },
    {
        "symbol": "META",
        "name": "Meta Platforms Inc.",
        "sector": "Communication",
        "exchange": "NASDAQ",
        "market_cap": 1_450_000,
        "price": 560.80,
        "change_pct_1d": 2.10,
        "pe_ratio": 26.2,
        "pb_ratio": 8.3,
        "ps_ratio": 8.8,
        "dividend_yield": 0.4,
        "revenue_growth": 22.1,
        "eps_growth": 73.4,
        "profit_margin": 34.9,
        "debt_to_equity": 0.10,
        "rsi_14": 67.4,
        "macd_signal": 3.10,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 38.1,
        "atr_pct": 1.5,
        "volume_ratio": 1.4,
    },
    {
        "symbol": "AMZN",
        "name": "Amazon.com Inc.",
        "sector": "Consumer",
        "exchange": "NASDAQ",
        "market_cap": 2_000_000,
        "price": 185.40,
        "change_pct_1d": 0.65,
        "pe_ratio": 42.5,
        "pb_ratio": 9.1,
        "ps_ratio": 3.2,
        "dividend_yield": 0.0,
        "revenue_growth": 12.5,
        "eps_growth": 212.0,
        "profit_margin": 7.8,
        "debt_to_equity": 0.61,
        "rsi_14": 59.3,
        "macd_signal": 0.85,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 27.5,
        "atr_pct": 1.3,
        "volume_ratio": 1.0,
    },
    {
        "symbol": "TSLA",
        "name": "Tesla Inc.",
        "sector": "Consumer",
        "exchange": "NASDAQ",
        "market_cap": 820_000,
        "price": 258.30,
        "change_pct_1d": -1.42,
        "pe_ratio": 72.1,
        "pb_ratio": 11.5,
        "ps_ratio": 7.9,
        "dividend_yield": 0.0,
        "revenue_growth": 1.2,
        "eps_growth": -23.0,
        "profit_margin": 8.5,
        "debt_to_equity": 0.12,
        "rsi_14": 38.2,
        "macd_signal": -2.50,
        "above_sma50": False,
        "above_sma200": False,
        "adx_14": 29.8,
        "atr_pct": 3.2,
        "volume_ratio": 1.6,
    },
    {
        "symbol": "BRK.B",
        "name": "Berkshire Hathaway B",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 890_000,
        "price": 395.10,
        "change_pct_1d": 0.18,
        "pe_ratio": 10.2,
        "pb_ratio": 1.5,
        "ps_ratio": 2.1,
        "dividend_yield": 0.0,
        "revenue_growth": 3.5,
        "eps_growth": 25.2,
        "profit_margin": 21.2,
        "debt_to_equity": 0.27,
        "rsi_14": 54.8,
        "macd_signal": 0.30,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 16.2,
        "atr_pct": 0.7,
        "volume_ratio": 0.8,
    },
    {
        "symbol": "JPM",
        "name": "JPMorgan Chase & Co.",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 700_000,
        "price": 220.30,
        "change_pct_1d": 0.52,
        "pe_ratio": 12.1,
        "pb_ratio": 2.0,
        "ps_ratio": 3.5,
        "dividend_yield": 2.2,
        "revenue_growth": 21.0,
        "eps_growth": 12.1,
        "profit_margin": 29.8,
        "debt_to_equity": 1.22,
        "rsi_14": 61.2,
        "macd_signal": 0.75,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 22.4,
        "atr_pct": 1.0,
        "volume_ratio": 1.1,
    },
    {
        "symbol": "V",
        "name": "Visa Inc.",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 560_000,
        "price": 281.40,
        "change_pct_1d": 0.25,
        "pe_ratio": 30.8,
        "pb_ratio": 14.5,
        "ps_ratio": 14.8,
        "dividend_yield": 0.8,
        "revenue_growth": 9.6,
        "eps_growth": 11.7,
        "profit_margin": 53.2,
        "debt_to_equity": 0.63,
        "rsi_14": 57.3,
        "macd_signal": 0.40,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 19.8,
        "atr_pct": 0.8,
        "volume_ratio": 0.9,
    },
    {
        "symbol": "XOM",
        "name": "Exxon Mobil Corporation",
        "sector": "Energy",
        "exchange": "NYSE",
        "market_cap": 490_000,
        "price": 112.50,
        "change_pct_1d": 0.90,
        "pe_ratio": 13.5,
        "pb_ratio": 2.1,
        "ps_ratio": 1.2,
        "dividend_yield": 3.5,
        "revenue_growth": -4.8,
        "eps_growth": -15.0,
        "profit_margin": 9.2,
        "debt_to_equity": 0.22,
        "rsi_14": 52.1,
        "macd_signal": 0.15,
        "above_sma50": True,
        "above_sma200": False,
        "adx_14": 14.3,
        "atr_pct": 1.1,
        "volume_ratio": 0.8,
    },
    {
        "symbol": "JNJ",
        "name": "Johnson & Johnson",
        "sector": "Healthcare",
        "exchange": "NYSE",
        "market_cap": 390_000,
        "price": 162.80,
        "change_pct_1d": -0.15,
        "pe_ratio": 15.2,
        "pb_ratio": 4.2,
        "ps_ratio": 4.1,
        "dividend_yield": 3.1,
        "revenue_growth": 4.2,
        "eps_growth": 7.5,
        "profit_margin": 18.8,
        "debt_to_equity": 0.48,
        "rsi_14": 43.5,
        "macd_signal": -0.30,
        "above_sma50": False,
        "above_sma200": False,
        "adx_14": 12.1,
        "atr_pct": 0.6,
        "volume_ratio": 0.7,
    },
    {
        "symbol": "UNH",
        "name": "UnitedHealth Group Inc.",
        "sector": "Healthcare",
        "exchange": "NYSE",
        "market_cap": 480_000,
        "price": 520.60,
        "change_pct_1d": 0.45,
        "pe_ratio": 21.4,
        "pb_ratio": 6.1,
        "ps_ratio": 1.4,
        "dividend_yield": 1.5,
        "revenue_growth": 8.5,
        "eps_growth": 12.3,
        "profit_margin": 6.5,
        "debt_to_equity": 0.71,
        "rsi_14": 60.2,
        "macd_signal": 0.90,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 25.3,
        "atr_pct": 0.9,
        "volume_ratio": 0.9,
    },
    {
        "symbol": "WMT",
        "name": "Walmart Inc.",
        "sector": "Consumer",
        "exchange": "NYSE",
        "market_cap": 680_000,
        "price": 85.20,
        "change_pct_1d": 0.32,
        "pe_ratio": 30.5,
        "pb_ratio": 6.8,
        "ps_ratio": 0.8,
        "dividend_yield": 1.2,
        "revenue_growth": 5.1,
        "eps_growth": 13.8,
        "profit_margin": 2.4,
        "debt_to_equity": 0.73,
        "rsi_14": 64.8,
        "macd_signal": 0.60,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 28.4,
        "atr_pct": 0.7,
        "volume_ratio": 0.8,
    },
    {
        "symbol": "PG",
        "name": "Procter & Gamble Co.",
        "sector": "Staples",
        "exchange": "NYSE",
        "market_cap": 390_000,
        "price": 162.10,
        "change_pct_1d": 0.10,
        "pe_ratio": 27.2,
        "pb_ratio": 8.3,
        "ps_ratio": 4.2,
        "dividend_yield": 2.4,
        "revenue_growth": 3.2,
        "eps_growth": 5.1,
        "profit_margin": 18.8,
        "debt_to_equity": 0.68,
        "rsi_14": 52.8,
        "macd_signal": 0.10,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 13.2,
        "atr_pct": 0.5,
        "volume_ratio": 0.7,
    },
    {
        "symbol": "HD",
        "name": "Home Depot Inc.",
        "sector": "Consumer",
        "exchange": "NYSE",
        "market_cap": 355_000,
        "price": 354.80,
        "change_pct_1d": -0.22,
        "pe_ratio": 24.1,
        "pb_ratio": 270.0,
        "ps_ratio": 2.5,
        "dividend_yield": 2.4,
        "revenue_growth": -3.5,
        "eps_growth": -6.2,
        "profit_margin": 14.2,
        "debt_to_equity": 99.9,
        "rsi_14": 47.5,
        "macd_signal": -0.40,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 17.5,
        "atr_pct": 0.9,
        "volume_ratio": 0.8,
    },
    {
        "symbol": "MA",
        "name": "Mastercard Incorporated",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 430_000,
        "price": 451.20,
        "change_pct_1d": 0.38,
        "pe_ratio": 35.2,
        "pb_ratio": 64.1,
        "ps_ratio": 16.2,
        "dividend_yield": 0.5,
        "revenue_growth": 12.5,
        "eps_growth": 13.1,
        "profit_margin": 46.4,
        "debt_to_equity": 2.57,
        "rsi_14": 58.4,
        "macd_signal": 0.55,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 21.3,
        "atr_pct": 0.8,
        "volume_ratio": 0.9,
    },
    {
        "symbol": "AVGO",
        "name": "Broadcom Inc.",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 780_000,
        "price": 165.50,
        "change_pct_1d": 1.20,
        "pe_ratio": 38.4,
        "pb_ratio": 11.2,
        "ps_ratio": 14.1,
        "dividend_yield": 1.3,
        "revenue_growth": 51.2,
        "eps_growth": 18.4,
        "profit_margin": 35.2,
        "debt_to_equity": 1.52,
        "rsi_14": 66.8,
        "macd_signal": 1.80,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 36.4,
        "atr_pct": 1.6,
        "volume_ratio": 1.3,
    },
    {
        "symbol": "LLY",
        "name": "Eli Lilly and Company",
        "sector": "Healthcare",
        "exchange": "NYSE",
        "market_cap": 760_000,
        "price": 832.50,
        "change_pct_1d": 0.75,
        "pe_ratio": 101.2,
        "pb_ratio": 64.8,
        "ps_ratio": 21.4,
        "dividend_yield": 0.6,
        "revenue_growth": 45.2,
        "eps_growth": 102.0,
        "profit_margin": 20.5,
        "debt_to_equity": 2.12,
        "rsi_14": 62.3,
        "macd_signal": 4.20,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 33.5,
        "atr_pct": 1.2,
        "volume_ratio": 1.1,
    },
    {
        "symbol": "COST",
        "name": "Costco Wholesale Corp.",
        "sector": "Staples",
        "exchange": "NASDAQ",
        "market_cap": 390_000,
        "price": 878.90,
        "change_pct_1d": 0.22,
        "pe_ratio": 50.8,
        "pb_ratio": 14.5,
        "ps_ratio": 1.4,
        "dividend_yield": 0.5,
        "revenue_growth": 9.1,
        "eps_growth": 18.2,
        "profit_margin": 2.9,
        "debt_to_equity": 0.39,
        "rsi_14": 59.2,
        "macd_signal": 0.80,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 22.1,
        "atr_pct": 0.8,
        "volume_ratio": 0.9,
    },
    {
        "symbol": "ABBV",
        "name": "AbbVie Inc.",
        "sector": "Healthcare",
        "exchange": "NYSE",
        "market_cap": 310_000,
        "price": 174.20,
        "change_pct_1d": 0.41,
        "pe_ratio": 55.2,
        "pb_ratio": None,
        "ps_ratio": 5.1,
        "dividend_yield": 3.7,
        "revenue_growth": 3.8,
        "eps_growth": 59.5,
        "profit_margin": 9.2,
        "debt_to_equity": 99.9,
        "rsi_14": 61.5,
        "macd_signal": 0.70,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 20.5,
        "atr_pct": 0.9,
        "volume_ratio": 0.8,
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 245_000,
        "price": 151.80,
        "change_pct_1d": 2.15,
        "pe_ratio": 172.0,
        "pb_ratio": 3.8,
        "ps_ratio": 8.8,
        "dividend_yield": 0.0,
        "revenue_growth": 17.6,
        "eps_growth": 850.0,
        "profit_margin": 3.5,
        "debt_to_equity": 0.03,
        "rsi_14": 68.1,
        "macd_signal": 2.30,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 41.2,
        "atr_pct": 2.8,
        "volume_ratio": 1.7,
    },
    {
        "symbol": "INTC",
        "name": "Intel Corporation",
        "sector": "Technology",
        "exchange": "NASDAQ",
        "market_cap": 95_000,
        "price": 22.80,
        "change_pct_1d": -0.88,
        "pe_ratio": None,
        "pb_ratio": 0.9,
        "ps_ratio": 1.2,
        "dividend_yield": 2.2,
        "revenue_growth": -0.9,
        "eps_growth": None,
        "profit_margin": -3.2,
        "debt_to_equity": 0.52,
        "rsi_14": 31.4,
        "macd_signal": -0.80,
        "above_sma50": False,
        "above_sma200": False,
        "adx_14": 28.5,
        "atr_pct": 2.4,
        "volume_ratio": 1.5,
    },
    {
        "symbol": "BAC",
        "name": "Bank of America Corp.",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 310_000,
        "price": 38.50,
        "change_pct_1d": 0.55,
        "pe_ratio": 12.8,
        "pb_ratio": 1.1,
        "ps_ratio": 2.8,
        "dividend_yield": 2.6,
        "revenue_growth": 8.2,
        "eps_growth": 10.5,
        "profit_margin": 22.4,
        "debt_to_equity": 1.35,
        "rsi_14": 58.2,
        "macd_signal": 0.20,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 19.5,
        "atr_pct": 1.2,
        "volume_ratio": 1.0,
    },
    {
        "symbol": "GS",
        "name": "Goldman Sachs Group",
        "sector": "Financials",
        "exchange": "NYSE",
        "market_cap": 180_000,
        "price": 520.40,
        "change_pct_1d": 0.68,
        "pe_ratio": 14.5,
        "pb_ratio": 1.5,
        "ps_ratio": 2.4,
        "dividend_yield": 2.1,
        "revenue_growth": 11.2,
        "eps_growth": 68.4,
        "profit_margin": 16.8,
        "debt_to_equity": 2.25,
        "rsi_14": 62.4,
        "macd_signal": 0.95,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 24.8,
        "atr_pct": 1.0,
        "volume_ratio": 1.0,
    },
    {
        "symbol": "SPY",
        "name": "SPDR S&P 500 ETF Trust",
        "sector": "ETF",
        "exchange": "NYSE",
        "market_cap": 560_000,
        "price": 498.20,
        "change_pct_1d": 0.24,
        "pe_ratio": 23.5,
        "pb_ratio": 4.1,
        "ps_ratio": 2.6,
        "dividend_yield": 1.3,
        "revenue_growth": 8.2,
        "eps_growth": 12.5,
        "profit_margin": None,
        "debt_to_equity": None,
        "rsi_14": 58.1,
        "macd_signal": 0.50,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 20.3,
        "atr_pct": 0.6,
        "volume_ratio": 1.0,
    },
    {
        "symbol": "QQQ",
        "name": "Invesco QQQ Trust",
        "sector": "ETF",
        "exchange": "NASDAQ",
        "market_cap": 280_000,
        "price": 421.80,
        "change_pct_1d": 0.65,
        "pe_ratio": 30.2,
        "pb_ratio": None,
        "ps_ratio": None,
        "dividend_yield": 0.6,
        "revenue_growth": None,
        "eps_growth": None,
        "profit_margin": None,
        "debt_to_equity": None,
        "rsi_14": 60.5,
        "macd_signal": 0.90,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 22.4,
        "atr_pct": 0.9,
        "volume_ratio": 1.0,
    },
    {
        "symbol": "GLD",
        "name": "SPDR Gold Trust",
        "sector": "Commodity",
        "exchange": "NYSE",
        "market_cap": 62_000,
        "price": 218.50,
        "change_pct_1d": 0.38,
        "pe_ratio": None,
        "pb_ratio": None,
        "ps_ratio": None,
        "dividend_yield": 0.0,
        "revenue_growth": None,
        "eps_growth": None,
        "profit_margin": None,
        "debt_to_equity": None,
        "rsi_14": 65.2,
        "macd_signal": 1.10,
        "above_sma50": True,
        "above_sma200": True,
        "adx_14": 30.2,
        "atr_pct": 0.8,
        "volume_ratio": 1.1,
    },
    {
        "symbol": "TLT",
        "name": "iShares 20+Yr Treas ETF",
        "sector": "ETF",
        "exchange": "NASDAQ",
        "market_cap": 48_000,
        "price": 88.40,
        "change_pct_1d": -0.48,
        "pe_ratio": None,
        "pb_ratio": None,
        "ps_ratio": None,
        "dividend_yield": 4.8,
        "revenue_growth": None,
        "eps_growth": None,
        "profit_margin": None,
        "debt_to_equity": None,
        "rsi_14": 35.2,
        "macd_signal": -0.60,
        "above_sma50": False,
        "above_sma200": False,
        "adx_14": 25.5,
        "atr_pct": 0.8,
        "volume_ratio": 1.3,
    },
]

# Sector definitions for heat map
SECTOR_MAP: dict[str, list[str]] = {
    "Technology": ["AAPL", "MSFT", "NVDA", "AVGO", "AMD", "INTC"],
    "Communication": ["GOOGL", "META"],
    "Consumer": ["AMZN", "TSLA", "WMT", "HD", "COST"],
    "Financials": ["BRK.B", "JPM", "V", "MA", "BAC", "GS"],
    "Healthcare": ["JNJ", "UNH", "LLY", "ABBV"],
    "Energy": ["XOM"],
    "Staples": ["PG"],
    "ETF/Other": ["SPY", "QQQ", "GLD", "TLT"],
}
